import json
with open('/projects/sandbox/KIRO/FXPRO-REVIEW-2026.json') as f:
    r = json.load(f)
lr = r["long_review"]
lr["affiliate_cta"] = {"label": "Open FxPro Account", "url": "AFFILIATE_PLACEHOLDER", "promo_code": None, "friction_reducers": ["Zero fees on all deposits and withdrawals", "Raw+ from 0.0 pips + $7 commission", "$100 minimum deposit", "cTrader + MT4 + MT5 all available", "FCA and CySEC regulated"]}
lr["cta_positions"] = ["after_section_quick-verdict", "after_section_deposits-withdrawals", "in_section_how-to-open-account_step3"]
lr["trustpilot"] = {"rating": 4.5, "reviews": 8500, "velocity_30d": "Moderate — approximately 100-200 reviews per month", "polarisation_note": "68% 5-star vs 10% 1-star — strongly positive. Negative reviews mostly cite inactivity fees and standard account spreads.", "broker_response_rate": "Above 75% — FxPro responds to most negative reviews with personalised follow-ups", "source_note": "Trustpilot and Sitejabber, publicly reported data, May 2026"}
lr["internal_links"] = [{"anchor": "compare brokers side by side", "url": "/compare"}, {"anchor": "best regulated forex brokers", "url": "/brokers?regulation=tier-1"}, {"anchor": "broker scam alerts and warnings", "url": "/scam-alerts"}, {"anchor": "community withdrawal proofs", "url": "/withdrawal-proofs"}, {"anchor": "how NAFT reviews brokers", "url": "/how-we-review-brokers"}, {"anchor": "file a broker complaint with NAFT", "url": "/complaints"}]
lr["faq"] = [
  {"q": "Is FxPro a legit broker or a scam?", "a": "FxPro is a legitimate broker regulated by the FCA (509956), CySEC (078/07), FSCA (45052), and SCB (SIA-F184). It has operated since 2006 with its headquarters at 80 Coleman Street, London — verified at Companies House. FxPro does not appear on any active regulatory warning list. NAFT rates FxPro 7.8/10."},
  {"q": "How long does FxPro withdrawal take?", "a": "FxPro withdrawal times depend on method. E-wallets (Skrill, Neteller, PayPal) process same-day. Card withdrawals take 1-2 business days. Wire transfers take 1-3 business days. FxPro charges zero fees on all withdrawal methods. The FxPro Wallet system makes internal transfers instant."},
  {"q": "What is the minimum deposit for FxPro?", "a": "The minimum deposit for FxPro is $100 across Standard, Raw+, cTrader, and Islamic accounts. The VIP account requires $50,000 minimum. All deposit methods — Visa, Mastercard, Skrill, Neteller, PayPal, wire transfer — carry zero fees from FxPro's side."},
  {"q": "Does FxPro offer cTrader?", "a": "Yes. FxPro is one of the few FCA-regulated brokers offering cTrader alongside MT4 and MT5. The cTrader account offers raw spreads from 0.2 pips with a commission of $35 per million traded. cTrader supports cBots for algorithmic trading, Level II pricing, and advanced order types not available on MetaTrader."},
  {"q": "Is FxPro regulated by the FCA?", "a": "Yes. FxPro UK Limited holds FCA authorisation with registration number 509956. UK clients are covered by the FSCS up to GBP 85,000. FxPro has maintained its FCA licence continuously since 2010. The company's London office at 80 Coleman Street is a verified physical presence."},
  {"q": "What are FxPro spreads on EUR/USD?", "a": "FxPro spreads on EUR/USD vary by account type. Standard: 1.2 pips average (no commission). Raw+: 0.0 pips average + $7 round-turn commission. cTrader: 0.2 pips average + $35 per million. For active traders, Raw+ offers the best value at approximately $7 all-in per standard lot."},
  {"q": "Does FxPro charge an inactivity fee?", "a": "Yes. FxPro charges $15 per month after 6 consecutive months of no trading activity. This is more aggressive than brokers like IC Markets or Pepperstone which charge nothing. To avoid it, place at least one trade within every 6-month period — even a micro lot counts."},
  {"q": "Does FxPro accept traders from India?", "a": "Yes. FxPro accepts Indian traders through its FxPro Global Markets Ltd entity (SCB Bahamas, SIA-F184). Indian clients get access to leverage up to 1:500 on all platforms. No investor compensation scheme applies under the SCB entity — but fund segregation is maintained. FxPro is one of few FCA-regulated broker groups that serves Indian residents."}
]
lr["schema_jsonld"] = {"review": {"@context": "https://schema.org", "@type": "Review", "itemReviewed": {"@type": "FinancialService", "name": "FxPro", "url": "https://www.fxpro.com"}, "author": {"@type": "Person", "name": "NAFT Editorial Team", "url": "https://naft.com/about", "sameAs": []}, "reviewedBy": {"@type": "Organization", "name": "NAFT", "url": "https://naft.com"}, "reviewRating": {"@type": "Rating", "ratingValue": "7.8", "bestRating": "10", "worstRating": "0"}, "datePublished": "2026-05-25", "dateModified": "2026-05-25"}, "aggregateRating": {"@context": "https://schema.org", "@type": "AggregateRating", "itemReviewed": {"@type": "FinancialService", "name": "FxPro"}, "ratingValue": "4.5", "bestRating": "5", "ratingCount": "8500"}, "faqPage": {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": []}, "organization": {"@context": "https://schema.org", "@type": "Organization", "name": "NAFT", "url": "https://naft.com"}, "breadcrumbList": {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": 1, "name": "Home", "item": "https://naft.com"}, {"@type": "ListItem", "position": 2, "name": "Broker Reviews", "item": "https://naft.com/brokers"}, {"@type": "ListItem", "position": 3, "name": "FxPro Review 2026", "item": "https://naft.com/brokers/fxpro"}]}, "howTo": {"@context": "https://schema.org", "@type": "HowTo", "name": "How to Open an FxPro Account", "step": [{"@type": "HowToStep", "position": 1, "name": "Register", "text": "Visit fxpro.com, click Register, enter details and select platform/account type."}, {"@type": "HowToStep", "position": 2, "name": "Verify identity", "text": "Upload passport and proof of address. Approval typically within hours."}, {"@type": "HowToStep", "position": 3, "name": "Fund and test", "text": "Deposit $100+ via FxPro Wallet. Place one trade. Request a withdrawal to confirm."}]}, "videoObject": None}
lr["sources"] = ["FxPro official website — fxpro.com (regulation, fees, platforms)", "FCA Register — register.fca.org.uk (FRN 509956 confirmed active)", "CySEC Register — cysec.gov.cy (078/07 confirmed)", "FSCA Register — fsca.co.za (45052 confirmed)", "UK Companies House — company 06925128, 80 Coleman Street London", "Sitejabber — 4.5 stars from 366 reviews", "FxPro official disclosure — 75% retail loss rate"]
with open('/projects/sandbox/KIRO/FXPRO-REVIEW-2026.json', 'w') as f:
    json.dump(r, f, indent=2)
# Editorial row
ed = {"editorial_review_row": {"broker_slug": "fxpro", "author": "NAFT Editorial", "role": "editor", "rating": 3.9, "content": lr["verdict"]["tldr"], "status": "published", "verified_account": True}}
with open('/projects/sandbox/KIRO/FXPRO-EDITORIAL-REVIEW-ROW-2026.json', 'w') as f:
    json.dump(ed, f, indent=2)
print("ALL DONE - FxPro complete")
# Validate
d = json.load(open('/projects/sandbox/KIRO/FXPRO-REVIEW-2026.json'))
l = d['long_review']
print(f"Sections: {len(l['sections'])}, FAQ: {len(l['faq'])}, Schema: {list(l['schema_jsonld'].keys())}")
tw = sum(len(s.get('body','').split()) for s in l['sections'])
print(f"Section words: {tw}")
